### ISSUE TITLE
Request: Publish new version

### ISSUE THREAD

**Issue by fosskers** [andrewthad/non-empty-containers#1]
Hi Andrew, could you publish a version of this to Hackage that includes the new functions and instances? In particular I'm looking for `Data.Set.NonEmpty.fromSet`, which doesn't seem to exist in `0.1.1.0`.

Thanks!

**Comment by fosskers** [comment]
Hi there, any thoughts on this?

**Comment by fosskers** [comment]
If you made me a co-maintainer on Hackage for this package, I could do it myself? (You've done this before, for `streaming-attoparsec` which I maintain.)

I'm asking because I'm trying to publish a project that depends on `non-empty-containers`.

**Comment by andrewthad** [comment]
Sorry about that. I just released `non-empty-containers-0.1.2.0` to hackage, but I've gone ahead and added you as a maintainer both on github and on hackage in case there are other things you end up needing to add.

**Comment by fosskers** [comment]
Thanks!
